// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoLab2.Models.DataContext;

namespace RepoLab2.Migrations
{
    [DbContext(typeof(TaskuriDbContext))]
    partial class TaskuriDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RepoLab2.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Important");

                    b.Property<int?>("TaskulId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("TaskulId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RepoLab2.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("RepoLab2.Models.TaskImportance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TasksImportance");
                });

            modelBuilder.Entity("RepoLab2.Models.Taskul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ClosedAt");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<int>("StatusId");

                    b.Property<int>("TaskImportanceId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskImportanceId");

                    b.ToTable("Taskuri");
                });

            modelBuilder.Entity("RepoLab2.Models.Comment", b =>
                {
                    b.HasOne("RepoLab2.Models.Taskul")
                        .WithMany("Comments")
                        .HasForeignKey("TaskulId");
                });

            modelBuilder.Entity("RepoLab2.Models.Taskul", b =>
                {
                    b.HasOne("RepoLab2.Models.Status")
                        .WithMany("Taskuri")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RepoLab2.Models.TaskImportance")
                        .WithMany("Taskuri")
                        .HasForeignKey("TaskImportanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
